[package]
name = "n64"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
mipsasm = "2.0.1"
pretty_env_logger = "0.4.0"
proc-bitfield = "0.2.2"
